name: Build, Test and Push to ECR

on:
  push:
    branches:
      - main

permissions:
  contents: read
  id-token: write

env:
  AWS_REGION: us-east-2
  AWS_ACCOUNT_ID: "221429122675"
  ECR_REPOSITORY: docker-aws-learning

jobs:
  build-test-push:
    runs-on: ubuntu-latest

    steps:
      - name: Download repository code
        uses: actions/checkout@v6

      - name: Build Docker image
        run: |
          docker build \
            -t docker-aws-learning:${{ github.sha }} .

      - name: Run container for testing
        run: |
          docker run -d \
            --name docker-aws-app \
            -p 3000:3000 \
            docker-aws-learning:${{ github.sha }}

      - name: Test application
        run: |
          sleep 5
          curl --fail http://localhost:3000

      - name: Show container logs
        if: always()
        run: docker logs docker-aws-app

      - name: Authenticate to AWS using OIDC
        uses: aws-actions/configure-aws-credentials@v6
        with:
          role-to-assume: arn:aws:iam::221429122675:role/GitHubActionsDockerECRRole
          aws-region: ${{ env.AWS_REGION }}

      - name: Login to Amazon ECR
        run: |
          aws ecr get-login-password --region "$AWS_REGION" |
          docker login \
            --username AWS \
            --password-stdin "$AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com"

      - name: Tag and push image to ECR
        run: |
          ECR_IMAGE="$AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/$ECR_REPOSITORY:${{ github.sha }}"
          docker tag "docker-aws-learning:${{ github.sha }}" "$ECR_IMAGE"
          docker push "$ECR_IMAGE"